export const DEFAULT_DATASET_ID = "default";

export const CANONICAL_NODE_TYPES = {
  SERVICE: "Service",
  FUNCTION: "Function",
  APPLICATION: "Application",
  INTEGRATION: "Integration",
  DIRECT_CHANNEL: "DirectChannel",
  HARDWARE_SPEC: "HardwareSpec",
  THIRD_PARTY: "ThirdParty"
} as const;

export const RELATIONSHIP_TYPES = {
  DEPENDS_ON: "DEPENDS_ON",
  HAS_FUNCTION: "HAS_FUNCTION",
  AVAILABLE_ON: "AVAILABLE_ON",
  RUN_BY: "RUN_BY",
  HAS_HARDWARE: "HAS_HARDWARE"
} as const;

export const KNOWN_COLUMN_TYPE_MAP: Record<string, string> = {
  "service name": CANONICAL_NODE_TYPES.SERVICE,
  service: CANONICAL_NODE_TYPES.SERVICE,
  "function name": CANONICAL_NODE_TYPES.FUNCTION,
  function: CANONICAL_NODE_TYPES.FUNCTION,
  app: CANONICAL_NODE_TYPES.APPLICATION,
  application: CANONICAL_NODE_TYPES.APPLICATION,
  integ: CANONICAL_NODE_TYPES.INTEGRATION,
  integration: CANONICAL_NODE_TYPES.INTEGRATION,
  "integration tool": CANONICAL_NODE_TYPES.INTEGRATION,
  dc: CANONICAL_NODE_TYPES.DIRECT_CHANNEL,
  "direct channel": CANONICAL_NODE_TYPES.DIRECT_CHANNEL
};
